---
swagger: "2.0"
info:
  description: "This is the API documentation of Konro HTTP interface"
  version: "1.0.0"
  title: "Konro API documentation"
#  contact:
#    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "app"
  description: "Everything about integrated applications"
- name: "rm"
  description: "Everything about the resource manager"
- name: "coord"
  description: "Cross-Konro coordination in a distributed setup"
schemes:
- "https"
- "http"
paths:
  /app/register:
    post:
      summary: "Register a new application"
      description: ""
      operationId: "register"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "appname"
        name: "appname"
        description: "Name of the application"
        required: true
        type: "string"
      - in: "appname"
        name: "appname"
        description: "Path to the binary"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
  /app/{appId}/info:
    get:
      summary: "Get information about an application"
      description: "Returns various information related to an application"
      operationId: "info"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of app to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "App not found"
