---
swagger: "2.0"
info:
  description: "This is the API documentation of Konro HTTP interface"
  version: "1.0.0"
  title: "Konro API documentation"
#  contact:
#    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "app"
  description: "Everything about integrated applications"
- name: "rm"
  description: "Everything about the resource manager"
- name: "coord"
  description: "Cross-Konro coordination in a distributed setup"
schemes:
- "https"
- "http"
paths:
  /app/register:
    post:
      tags:
        - "app"
      summary: "Register a new application"
      description: ""
      operationId: "register"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "appname"
        name: "appname"
        description: "Name of the application"
        required: true
        type: "string"
      - in: "binary_path"
        name: "binary_path"
        description: "Path to the binary"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid request."
        503:
          description: "No resources available."
  /app/{app_id}/info:
    get:
      tags:
        - "app"
      summary: "Get information about an application"
      description: "Returns various information related to an application"
      operationId: "info"
      produces:
      - "application/json"
      parameters:
      - name: "app_id"
        in: "app_id"
        description: "ID of app to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Application"
        400:
          description: "Invalid ID supplied"
        404:
          description: "App not found"

  /coord/get_nodes:
    get:
      tags:
        - "coord"
      summary: "Get information about nodes in the cluster"
      description: "Returns all the nodes known by the host"
      operationId: "get_nodes"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Node"
  /coord/publish_nodes:
    get:
      tags:
        - "coord"
      summary: "Provide information about Konro nodes to the cluster"
      description: ""
      operationId: "publish_nodes"
      produces:
      - "application/json"
      parameters:
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Node"
      responses:
        200:
          description: "Successful operation"
          schema:

definitions:
  Application:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      binary_path:
        type: "string"
  Node:
    type: "object",
    properties:
      hostname: 
        type: "string"
      ipaddr: 
        type: "string"
      status:
        type: "integer"
        format: "int8"
      last_seen:
        type: "integer"
        description: "UNIX timestamp"
        format: "int64"
      
